Update backup tool

diff --git a/tools/backup b/tools/backup
--- a/tools/backup
+++ b/tools/backup
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # This tool is useful for making backups using rsync.
 # It's a bit annoying to have to read the manual each time.
@@ -12,23 +12,26 @@
 # Maybe need to abort if an old script is detected?
 # Ideally they'll all use the exact same script.
 
-__private_backup_check_dependencies() {
-    if ! command -v date &> /dev/null; then
-	echo "Error: 'date' is not installed. Aborting script." >&2
-	return 1
-    fi
+if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+    echo "ERROR: This script must be run, not sourced!" >&2
+    # Use 'return' to stop execution within the sourced context
+    return 1
+fi
 
-    if ! command -v rsync &> /dev/null; then
-	echo "Error: 'rsync' is not installed. Aborting script." >&2
-	return 1
-    fi
-}
+if ! command -v date &> /dev/null; then
+    echo "Error: 'date' is not installed. Aborting script." >&2
+    return 1
+fi
 
-__private_backup_do_incremental_backup() {
+if ! command -v rsync &> /dev/null; then
+    echo "Error: 'rsync' is not installed. Aborting script." >&2
+    return 1
+fi
 
-    __private_backup_check_dependencies
+do_incremental_backup() {
 
-    local DATE_TAG=`date "+%Y-%m-%dT%H-%M-%S"`
+    local DATE_TAG=""
+    DATE_TAG=$(date "+%Y-%m-%dT%H-%M-%S")
 
     local SOURCE_PATH="$1"
     local DESTINATION_PATH="$2"
@@ -68,7 +71,7 @@ EOF
 	"$SOURCE_PATH" "$DESTINATION_PATH/backup-$DATE_TAG"
 
     rm -f "$DESTINATION_PATH/latest"
-    ln -s "$DESTINATION_PATH/backup-$date" "$DESTINATION_PATH/latest"
+    ln -s "$DESTINATION_PATH/backup-$DATE_TAG" "$DESTINATION_PATH/latest"
 }
 
 backup() {
@@ -83,5 +86,7 @@ backup() {
 	return 1
     fi
 
-    __private_backup_do_incremental_backup "${@:1}"
+    do_incremental_backup "${@:1}"
 }
+
+backup "$@"
