Fixes for repos

diff --git a/tools/repos b/tools/repos
--- a/tools/repos
+++ b/tools/repos
@@ -2,12 +2,12 @@
 set -euo pipefail
 
 # Preconditions
-__private_repos_assert_dependencies() {
-	command -v git >/dev/null 2>&1 || { echo >&2 "Error: Git is not installed."; exit 1 }
-	command -v find >/dev/null 2>&1 || { echo >&2 "Error: find is not installed."; exit 1 }
-}
+#__private_repos_assert_dependencies() {
+#	command -v git >/dev/null 2>&1 || { echo >&2 "Error: Git is not installed."; exit 1 }
+#	command -v find >/dev/null 2>&1 || { echo >&2 "Error: find is not installed."; exit 1 }
+#}
 
-__private_repos_assert_dependencies
+#__private_repos_assert_dependencies
 
 # === CONFIG SETTINGS ===
 
@@ -15,7 +15,7 @@ REPOS_PATHS_FILE=~/.config/repos/paths
 
 # The ignore file lists out paths to ignore when processing repos
 # TODO: Enable this
-# REPOS_IGNORE_FILE=~/.config/repos/ignore
+REPOS_IGNORE_FILE=~/.config/repos/ignore
 
 # === Helper Functions ===
 
@@ -40,7 +40,7 @@ __private_repos_fetch () {
 		repo="$REPLY"
 		repo="${repo/#\~/$HOME}"
 
-		echo "\\033[36m=== $repo ===\\033[0m"
+		printf "\\033[36m=== %s ===\\033[0m" "$repo"
 
 		git -C "$repo" fetch --dry-run --verbose
 	done < "$REPOS_PATHS_FILE"
@@ -63,6 +63,12 @@ __private_repos_add () {
 		# Keep it sorted.
 		sort -o "$REPOS_PATHS_FILE" "$REPOS_PATHS_FILE"
 	fi
+}
+
+__private_repos_repo_is_in_paths_file () {
+	repo="$1"
+	rel_path="$(__private_repos_get_rel_path "$repo")"
+	grep -qx "$rel_path" "$REPOS_PATHS_FILE"
 }
 
 # Search for repositories relative to the current directory.
@@ -127,7 +133,7 @@ __private_repos_status_long () {
 		repo="$REPLY"
 		repo="${repo/#\~/$HOME}"  # Replace ~ with $HOME
 		echo ""
-		echo "\\033[36m=== $repo ===\\033[0m"
+		printf "\\033[36m=== %s ===\\033[0m" "$repo"
 
 		git -C "$repo" remote -v
 
@@ -215,7 +221,7 @@ __private_repos_status_of_repo () {
 	if [ $dirty_only = false ] || [ $is_clean = false ]; then
 
 		local clean_status=""
-		clean_status=$($is_clean && echo "\033[32mCLEAN\033[0m" || echo "\033[31mDIRTY\033[0m")
+		clean_status=$($is_clean && printf "\033[32mCLEAN\033[0m" || printf "\033[31mDIRTY\033[0m")
 		echo "$clean_status $repo"
 
 		# Begin processing remote changes. Compare branches with what is on the various remotes.
@@ -226,7 +232,7 @@ __private_repos_status_of_repo () {
 		fi
 
 		if [ -z "$remotes" ]; then
-			echo "\033[31mwarn\033[0m No remotes. You should configure an upstream remote."	
+			printf "\033[31mwarn\033[0m No remotes. You should configure an upstream remote."	
 		fi
 
 		for remote in "${remotes[@]}"; do
@@ -235,7 +241,7 @@ __private_repos_status_of_repo () {
 			commits="$(git -C "$repo" log --branches --not --remotes --oneline --simplify-by-decoration --decorate --graph)"
 
 			if [ -n "$commits" ]; then
-				echo "- remote: $remote is \033[31mmissing\033[0m:"
+				printf "- remote: %s is \033[31mmissing\033[0m:" "$remote"
 				echo "$commits"
 			fi	
 
@@ -258,7 +264,7 @@ __private_repos_status () {
 	while IFS= read -r; do
 		local repo="$REPLY"
 		local repo="${repo/#\~/$HOME}"
-		__private_repos_status_of_repo "$repo" "${@}"
+		__private_repos_status_of_repo "$repo" "$@"
 		counter=$((counter + 1))
 	done < "$REPOS_PATHS_FILE"
 
@@ -309,6 +315,13 @@ __private_repos_audit_policy_origin_reachable () {
 	local repo="$1"
 }
 
+__private_repos_audit_policy_all_repos_are_registered_check_repo_is_registered () {
+	repo="$1"
+	if ! __private_repos_repo_is_in_paths_file "$repo" ; then
+		echo "Warning: Policy violation. Repo: $repo is not in paths file."
+	fi
+}
+
 __private_repos_audit_policy_all_repos_are_registered () {
 	echo "Policy: All repositories are registered with the repos tool."
 
@@ -316,10 +329,15 @@ __private_repos_audit_policy_all_repos_are_registered () {
 	# Check these are all registered with the repos tool...
 	# Report anything that isn't registered.
 
-	
+	while IFS= read -r -d ''; do
+		repo_dir="$(dirname -- "$REPLY")"
+		repo="${repo_dir%/.}"
+		echo "Evaluating repo: $repo"
+		__private_repos_audit_policy_all_repos_are_registered_check_repo_is_registered "$repo"
+	done < <(find . -name .git -print0)
 }
 
-__private_repos_audit() {
+__private_repos_audit () {
 	echo "Running git repo audit..."
 
 	# Audit registration policies
